In [41]:
import pandas as pd

In [50]:
import pandas as pd

location='https://github.com/Samikpan/PUBPOL542/raw/main/'
Financial_data=location+'Financial_Development_FD.xlsx'
Financial_index = pd.read_excel(Financial_data,'Financial Development (FD)')

In [51]:
Financial_indexTest=Financial_index.copy()

In [52]:
Financial_indexTest.describe()

,Financial Development Index,Unnamed: 2,Financial Institutions Access Index,Unnamed: 4,Financial Institutions Depth Index,Unnamed: 6,Financial Institutions Efficiency Index,Unnamed: 8,Financial Institutions Index,Unnamed: 10,Financial Markets Access Index,Unnamed: 12,Financial Markets Depth Index,Unnamed: 14,Financial Markets Efficiency Index,Unnamed: 16,Financial Markets Index,Unnamed: 18
count,180.000000,0.0,180.000000,0.0,180.000000,0.0,180.000000,0.0,180.000000,0.0,180.000000,0.0,180.000000,0.0,180.000000,0.0,180.000000,0.0
mean,0.324801,NaN,0.374124,NaN,0.267571,NaN,0.620733,NaN,0.434526,NaN,0.197557,NaN,0.228618,NaN,0.173400,NaN,0.202756,NaN
std,0.225319,NaN,0.273026,NaN,0.260356,NaN,0.144614,NaN,0.212123,NaN,0.268653,NaN,0.288978,NaN,0.302054,NaN,0.259767,NaN
min,0.046520,NaN,0.000000,NaN,0.000000,NaN,0.020803,NaN,0.091276,NaN,0.000000,NaN,0.000000,NaN,0.000000,NaN,0.000000,NaN
25%,0.143710,NaN,0.118856,NaN,0.082198,NaN,0.535991,NaN,0.253588,NaN,0.000000,NaN,0.009627,NaN,0.000000,NaN,0.004776,NaN
50%,0.250494,NaN,0.356603,NaN,0.172724,NaN,0.646259,NaN,0.403629,NaN,0.017138,NaN,0.094868,NaN,0.000000,NaN,0.070486,NaN
75%,0.442935,NaN,0.569485,NaN,0.339426,NaN,0.736017,NaN,0.589137,NaN,0.395363,NaN,0.361527,NaN,0.180137,NaN,0.330836,NaN
max,0.963959,NaN,1.000000,NaN,1.000000,NaN,0.838923,NaN,0.978640,NaN,1.000000,NaN,0.999248,NaN,1.000000,NaN,0.912713,NaN

In [53]:
Financial_indexTest.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 19 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Unnamed: 0                               180 non-null    object
 1   Financial Development Index              180 non-null    float64
 2   Unnamed: 2                               0 non-null      float64
 3   Financial Institutions Access Index      180 non-null    float64
 4   Unnamed: 4                               0 non-null      float64
 5   Financial Institutions Depth Index       180 non-null    float64
 6   Unnamed: 6                               0 non-null      float64
 7   Financial Institutions Efficiency Index  180 non-null    float64
 8   Unnamed: 8                               0 non-null      float64
 9   Financial Institutions Index             180 non-null    float64
 10  Unnamed: 10                              0 non-null      float64
 11  Financial Markets Access Index           180 non-null    float64
 12  Unnamed: 12                              0 non-null      float64
 13  Financial Markets Depth Index            180 non-null    float64
 14  Unnamed: 14                              0 non-null      float64
 15  Financial Markets Efficiency Index       180 non-null    float64
 16  Unnamed: 16                              0 non-null      float64
 17  Financial Markets Index                  180 non-null    float64
 18  Unnamed: 18                              0 non-null      float64
dtypes: float64(18), object(1)
memory usage: 26.8+ KB

In [54]:
Financial_indexTest[:]

,Unnamed: 0,Financial Development Index,Unnamed: 2,Financial Institutions Access Index,Unnamed: 4,Financial Institutions Depth Index,Unnamed: 6,Financial Institutions Efficiency Index,Unnamed: 8,Financial Institutions Index,Unnamed: 10,Financial Markets Access Index,Unnamed: 12,Financial Markets Depth Index,Unnamed: 14,Financial Markets Efficiency Index,Unnamed: 16,Financial Markets Index,Unnamed: 18
0,Albania,0.199178,NaN,0.398397,NaN,0.130727,NaN,0.606880,NaN,0.385934,NaN,0.000000,NaN,0.013138,NaN,0.000000,NaN,0.004867,NaN
1,Algeria,0.144825,NaN,0.098856,NaN,0.071766,NaN,0.749048,NaN,0.282371,NaN,0.004115,NaN,0.001256,NaN,0.000000,NaN,0.001785,NaN
2,Angola,0.156810,NaN,0.202931,NaN,0.056864,NaN,0.573909,NaN,0.268359,NaN,0.006514,NaN,0.100481,NaN,0.000000,NaN,0.039313,NaN
3,Antigua and Barbuda,0.314413,NaN,0.641449,NaN,0.308106,NaN,0.825533,NaN,0.616899,NaN,0.000000,NaN,0.000000,NaN,0.000000,NaN,0.000000,NaN
4,Argentina,0.321531,NaN,0.380714,NaN,0.191181,NaN,0.606800,NaN,0.402824,NaN,0.562564,NaN,0.074320,NaN,0.063742,NaN,0.228041,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,Vanuatu,0.196999,NaN,0.416207,NaN,0.127696,NaN,0.588039,NaN,0.386525,NaN,0.000000,NaN,0.000000,NaN,0.000000,NaN,0.000000,NaN
176,"Venezuela, Republica Bolivariana de",0.234540,NaN,0.399978,NaN,0.166630,NaN,0.573756,NaN,0.391386,NaN,0.007348,NaN,0.156618,NaN,0.026689,NaN,0.068798,NaN
177,Vietnam,0.386524,NaN,0.153383,NaN,0.306941,NaN,0.772031,NaN,0.404434,NaN,0.415299,NaN,0.220129,NaN,0.441265,NaN,0.353953,NaN
178,"Yemen, Republic of",0.121234,NaN,0.047037,NaN,0.018556,NaN,0.612876,NaN,0.201424,NaN,0.000000,NaN,0.098381,NaN,0.000000,NaN,0.036446,NaN
179,Zambia,0.117064,NaN,0.105730,NaN,0.075592,NaN,0.452135,NaN,0.201840,NaN,0.000000,NaN,0.068611,NaN,0.007700,NaN,0.027847,NaN

In [55]:
cols = [2,4,6,8,10,12,14,16,18]
Financial_indexTest.drop(Financial_index.columns[cols],axis=1,inplace=True)

In [56]:
Financial_indexTest[:]

,Unnamed: 0,Financial Development Index,Financial Institutions Access Index,Financial Institutions Depth Index,Financial Institutions Efficiency Index,Financial Institutions Index,Financial Markets Access Index,Financial Markets Depth Index,Financial Markets Efficiency Index,Financial Markets Index
0,Albania,0.199178,0.398397,0.130727,0.606880,0.385934,0.000000,0.013138,0.000000,0.004867
1,Algeria,0.144825,0.098856,0.071766,0.749048,0.282371,0.004115,0.001256,0.000000,0.001785
2,Angola,0.156810,0.202931,0.056864,0.573909,0.268359,0.006514,0.100481,0.000000,0.039313
3,Antigua and Barbuda,0.314413,0.641449,0.308106,0.825533,0.616899,0.000000,0.000000,0.000000,0.000000
4,Argentina,0.321531,0.380714,0.191181,0.606800,0.402824,0.562564,0.074320,0.063742,0.228041
...,...,...,...,...,...,...,...,...,...,...
175,Vanuatu,0.196999,0.416207,0.127696,0.588039,0.386525,0.000000,0.000000,0.000000,0.000000
176,"Venezuela, Republica Bolivariana de",0.234540,0.399978,0.166630,0.573756,0.391386,0.007348,0.156618,0.026689,0.068798
177,Vietnam,0.386524,0.153383,0.306941,0.772031,0.404434,0.415299,0.220129,0.441265,0.353953
178,"Yemen, Republic of",0.121234,0.047037,0.018556,0.612876,0.201424,0.000000,0.098381,0.000000,0.036446
179,Zambia,0.117064,0.105730,0.075592,0.452135,0.201840,0.000000,0.068611,0.007700,0.027847

In [71]:
Financial_indexTest.rename(columns={'Unnamed: 0':'Country'}, inplace = True) ### renaming an unnamed column

In [72]:
Financial_indexTest[:]

,Country,Financial Development Index,Financial Institutions Access Index,Financial Institutions Depth Index,Financial Institutions Efficiency Index,Financial Institutions Index,Financial Markets Access Index,Financial Markets Depth Index,Financial Markets Efficiency Index,Financial Markets Index
0,Albania,0.199178,0.398397,0.130727,0.606880,0.385934,0.000000,0.013138,0.000000,0.004867
1,Algeria,0.144825,0.098856,0.071766,0.749048,0.282371,0.004115,0.001256,0.000000,0.001785
2,Angola,0.156810,0.202931,0.056864,0.573909,0.268359,0.006514,0.100481,0.000000,0.039313
3,Antigua and Barbuda,0.314413,0.641449,0.308106,0.825533,0.616899,0.000000,0.000000,0.000000,0.000000
4,Argentina,0.321531,0.380714,0.191181,0.606800,0.402824,0.562564,0.074320,0.063742,0.228041
...,...,...,...,...,...,...,...,...,...,...
175,Vanuatu,0.196999,0.416207,0.127696,0.588039,0.386525,0.000000,0.000000,0.000000,0.000000
176,"Venezuela, Republica Bolivariana de",0.234540,0.399978,0.166630,0.573756,0.391386,0.007348,0.156618,0.026689,0.068798
177,Vietnam,0.386524,0.153383,0.306941,0.772031,0.404434,0.415299,0.220129,0.441265,0.353953
178,"Yemen, Republic of",0.121234,0.047037,0.018556,0.612876,0.201424,0.000000,0.098381,0.000000,0.036446
179,Zambia,0.117064,0.105730,0.075592,0.452135,0.201840,0.000000,0.068611,0.007700,0.027847

In [70]:
Financial_indexTest.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 10 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Country                                  180 non-null    object
 1   Financial Development Index              180 non-null    float64
 2   Financial Institutions Access Index      180 non-null    float64
 3   Financial Institutions Depth Index       180 non-null    float64
 4   Financial Institutions Efficiency Index  180 non-null    float64
 5   Financial Institutions Index             180 non-null    float64
 6   Financial Markets Access Index           180 non-null    float64
 7   Financial Markets Depth Index            180 non-null    float64
 8   Financial Markets Efficiency Index       180 non-null    float64
 9   Financial Markets Index                  180 non-null    float64
dtypes: float64(9), object(1)
memory usage: 14.2+ KB

In [75]:
Financial_FinalData = Financial_indexTest.iloc[:, [0,1,4]]

In [76]:
Financial_FinalData

,Country,Financial Development Index,Financial Institutions Efficiency Index
0,Albania,0.199178,0.606880
1,Algeria,0.144825,0.749048
2,Angola,0.156810,0.573909
3,Antigua and Barbuda,0.314413,0.825533
4,Argentina,0.321531,0.606800
...,...,...,...
175,Vanuatu,0.196999,0.588039
176,"Venezuela, Republica Bolivariana de",0.234540,0.573756
177,Vietnam,0.386524,0.772031
178,"Yemen, Republic of",0.121234,0.612876
179,Zambia,0.117064,0.452135